### ISSUE TITLE
Lags behind Platform driven scrolling.

### ISSUE THREAD

**Issue by jordwalke** [joeytwiddle/sexy_scroller.vim#12]
For example, in MacVim, the native mouse/trackpad driven scrolling of the operating system fights with this plugin. It would just be better to disable this plugin whenever the cursor moves off the screen, or even disable it entirely except when invoked via a keyboard mapping. In general, I would suggest accepting this [pull request](https://github.com/joeytwiddle/sexy_scroller.vim/pull/9) which would allow people to completely disable this plugin, except when explicitly invoking the scroll function. (Note it would also address the `incsearch` issue). The easing function is nice, but I'd prefer to use the animation only in cases when it can be done in a very high quality manner (not fighting with the OS driven scrolling, and not when `incsearch` is used). If that means I could only use this via an explicit keyboard mapping for animated scrolling, then it would be worth it IMHO.

**Comment by joeytwiddle** [comment]
I had forgotten about the branch. I didn't really understand it!

Since you find it useful, I have now merged it.

Mouse wheel scrolling is already discussed in [issue #8](https://github.com/joeytwiddle/sexy_scroller.vim/issues/8), so I am closing this issue. Unless you mean something else by "OS driven scrolling"...?

**Comment by jordwalke** [comment]
Yes, I was referring to mouse/trackpad driven scrolling which was not fixed at the time I posted this.
